### ISSUE TITLE
Midi control of  mpc panel

### ISSUE THREAD

**Issue by MrThraz** [izzyreal/mpc#1]
Feature needed for control of emulator in a studio envorment. As far as I can tell one cannot control the front panel of the vmpc through midi.

**Comment by izzyreal** [comment]
Sorry for not picking this up @MrThraz . The project is now in a better state to implement new features, so I hope to pick it up somewhere in the next month or 2.

**Comment by izzyreal** [comment]
An original implementation of the MIDISW screen has finally been added in 9a64dcc1c818c6254d076106b9619c5e03c92aa6.

The slider was already controllable via every MIDI CC, which has now been restricted to only listen to channel 7 as per MPC2000XL's MIDI implementation chart.

I'll close this ticket and create a new one dedicated to controlling every button, pot and the datawheel.
