### ISSUE TITLE
Implement Convert Song to Seq screen

### ISSUE THREAD

**Issue by izzyreal** [izzyreal/mpc#112]
Also see https://github.com/izzyreal/vmpc-juce/issues/98. After wrapping up this ticket, make sure @c3ntr0n800 knows about it.

**Comment by izzyreal** [comment]
Resolved in 782911e1fa6be31058feae77710111dcbd14f321.

@c3ntr0n800 I'm going to publish a v0.5.4 release asap and it should have working Convert Song to Seq functionality.

**Comment by izzyreal** [comment]
@c3ntr0n800 v0.5.4 released. I hope it works well 😄 Let me know if you encounter any issues.

**Comment by c3ntr0n800** [comment]
Nice, great to see it was added quickly (and thanks for the shout-out too!) However, it appears that attempting to play converted sequences on a previous project of mine causes a crash, but it works correctly on your demos and new projects. I finished that previous project anyways, so it's not that big of deal for me.

**Comment by izzyreal** [comment]
@c3ntr0n800 Can you send me your project?

**Comment by c3ntr0n800** [comment]
@izzyreal (Excuse the sloppiness, I was learning while making it)
[Uploading project.zip…]()

**Comment by izzyreal** [comment]
<img width="492" alt="image" src="https://github.com/izzyreal/mpc/assets/3707432/206e9c8c-f759-4627-a1cf-538bd8711838">
I see this, is it still uploading or did something go wrong?

**Comment by c3ntr0n800** [comment]
I guess it got stuck... I edited the message with a link to it uploaded somewhere else.

**Comment by izzyreal** [comment]
@c3ntr0n800 Nice beat! So far it doesn't crash when convert the song to a seq, but I can certainly see a bug, so I will address that. In the meantime, can you let me know the exact steps that make it crash for you? Is the crash reproducible?

**Comment by c3ntr0n800** [comment]
I appreciate the compliment, it turned out better than I was expecting it to.

As for how it crashes on my end, it's when I try cycling through events in the step editor on a bugged converted sequence.

**Comment by izzyreal** [comment]
@c3ntr0n800 Right, ok, that makes sense with another observation I just had. I've just minimized the problem, I'm about to address it. I hope to release a v0.5.4.1 patch today or tomorrow.

**Comment by c3ntr0n800** [comment]
Excellent, that's great to hear! Respect for quickly fixing this bug.

**Comment by izzyreal** [comment]
@c3ntr0n800 I dug in, and honestly there were so many bugs in inserting bars and changing time signatures that it was a bit of a miracle that anything was working properly at all 😂  Thanks again for providing that real life beat, that really helps with battle-testing and finding nasty bugs. I think things should be fixed in dec98145d26055e5cc8c7cf8c4888a9d4e5dddbb. At the very least I'm able to enjoy your funky song in full swing after converting it to a sequence.

I'm building a v0.5.5 release as we speak. Keep an eye out and I'll notify you when it's ready for download,

**Comment by izzyreal** [comment]
Resolved in 6d0acac2c7543e097aaf92d994115b2ee6acabe4

@c3ntr0n800 You can grab the latest v0.5.5 installer from https://izmar.nl/downloads

Would be great to get your confirmation all is good!

**Comment by c3ntr0n800** [comment]
I don't see any more crashes occurring when converting sequences. Very good!

**Comment by izzyreal** [comment]
Glad to hear that, let me know if you run into anything.
