### ISSUE TITLE
Offset MIDI mapping

### ISSUE THREAD

**Issue by SamuelSHrk** [izzyreal/mpc#118]
I have an AKAI MPD218 MIDI controller and was hoping to use it with the VMPC but the MIDI mapping doesnt correlate between each other very well. If I hit PAD 1 on the controller, it goes to PAD 2 in the VST. The same for the other pads in the plugin, to the point where PAD 1 and PAD 16 on my controller dont trigger anything.

**Comment by izzyreal** [comment]
Hi @SamuelSHrk , do you know what pad layout you have on your MPD218? As in, which pad maps to which MIDI note?

The default for VMPC2000XL is a chromatic mapping starting at note 37 for pad 1, up to note 98 for pad 64. In theory you should be able to use any pad/MIDI controller as long as the mapping is configured correctly on both sides. So you can either change the mapping on your controller, or you can change the mapping in VMPC2000XL.

**Comment by SamuelSHrk** [comment]
It seems like to me the way the VMPC is mapped is that its offset by one pad that I press on the MIDI controller, from everything I used like TAL-DRUM, Poise or Speedrum everything is mapped correctly but this particular software is acting strange in receiving USB-MIDI signals. Therefore, the issue is definitely in the VMPC.
Also I keep the PAD BANK on the MPD218 at A, in which it works like a key transposer. I will try to configure it to the best of my abilities.

**Comment by izzyreal** [comment]
> which pad maps to which MIDI note?

This would be very helpful, so I know what note each pad of your controller maps to.

**Comment by SamuelSHrk** [comment]
so if i hit PAD 1 on the MPD218 it goes to PAD 2 on the VMPC, so its off by one note.

**Comment by izzyreal** [comment]
I mean something different, unrelated to VMPC. When you hit a pad on your controller, it triggers a MIDI note on event. I would like to know which note numbers are produced for each pad.

**Comment by SamuelSHrk** [comment]
the PAD 1 note for PAD BANK A is C3

**Comment by izzyreal** [comment]
MIDI note 60?

**Comment by SamuelSHrk** [comment]
Im not sure. how do I see midi note numbers like that?

**Comment by izzyreal** [comment]
On Windows you can use MIDI OX: http://www.midiox.com/moxdown.htm
On macOS you use MIDI Monitor: https://www.snoize.com/midimonitor/

Alternatively you might be able to find the default mapping in the documentation of your controller, or maybe it comes with configuration software that allows you to see the whole mapping in one go.

**Comment by SamuelSHrk** [comment]
I just downloaded it and i cant really find what the MIDI note numbe
![image_2022-08-13_180930758](https://user-images.githubusercontent.com/43790833/184512297-04d245f6-9587-4c7d-b776-c907fb962126.png)
r is.

**Comment by izzyreal** [comment]
@SamuelSHrk I'm sorry for not responding earlier, I completely missed your reply.

The note number is in hex in the DATA1 column for a note on or note off.

By the way, I've been doing some work on the general inconvenience of using pad controllers, in preparation for the upcoming v0.5 release. So I would love to incorporate proper support for the MPD218 as well.

I think in MIDI-OX you can filter out the channel aftertouch messages, so you only see note on/off. If you do that, and press all pads once, starting at pad 1 in the bottom-left, working your way up in ascending order to pad 16 in the top-right, and send me a screenshot of the whole list in MIDI-OX, I can start adding bank A of your controller to VMPC2000XL for a start.

**Comment by SamuelSHrk** [comment]
> @SamuelSHrk I'm sorry for not responding earlier, I completely missed your reply.
> 
> The note number is in hex in the DATA1 column for a note on or note off.
> 
> By the way, I've been doing some work on the general inconvenience of using pad controllers, in preparation for the upcoming v0.5 release. So I would love to incorporate proper support for the MPD218 as well.
> 
> I think in MIDI-OX you can filter out the channel aftertouch messages, so you only see note on/off. If you do that, and press all pads once, starting at pad 1 in the bottom-left, working your way up in ascending order to pad 16 in the top-right, and send me a screenshot of the whole list in MIDI-OX, I can start adding bank A of your controller to VMPC2000XL for a start.
> 

That's awesome! I'll def check later and use MIDI-OX to send you the screenshot and maybe even the logs.

**Comment by izzyreal** [comment]
You know what, I need a few of these controllers around so I ordered an MPD218. No need to do the MIDI-OX stuff, and then I can also easily add everything that can be added (all banks, some dials).

I'll keep you posted here. Thanks a lot for your efforts!

**Comment by SamuelSHrk** [comment]
> You know what, I need a few of these controllers around so I ordered an MPD218. No need to do the MIDI-OX stuff, and then I can also easily add everything that can be added (all banks, some dials).
> 
> I'll keep you posted here. Thanks a lot for your efforts!

Yeah no problem, in fact part of the reason I got an MPD218 is so I can use this awesome product so I think it's awesome you're getting one yourself. Do tell me how it goes, I'm curious!

**Comment by SamuelSHrk** [comment]
Hi Izzy, everything been working OK with your MPD218?

**Comment by izzyreal** [comment]
Hi @SamuelSHrk, I forgot to update this thread, sorry 'bout that! Yes, in fact, here's a preview for the upcoming v0.5.0 release, and it has a built-in MIDI controller preset for the MPD218.

https://drive.google.com/file/d/1AcYp8iDgynxLN3A8r_0zAkWl2VyQdJ1J/view?usp=share_link

If everything works OK, VMPC2000XL should detect it when you hook up an MPD218 and ask you if you want to switch to that mapping. To actually see and tweak the mapping, you can go to VMPC settings (Shift + 0) and then the MIDI tab (F5).

**Comment by SamuelSHrk** [comment]
@izzyreal awesome! I appreciate it so much. Thank you for your efforts. However, I will be at work for another 9 hours or so. I will be back with an update sometime afterwards.

**Comment by izzyreal** [comment]
That would be great. Don't hesitate to ask any questions or give other kind of feedback.

**Comment by SamuelSHrk** [comment]
![image_2022-12-09_175339618](https://user-images.githubusercontent.com/43790833/206808491-9e746aed-6bfe-45de-8032-ddc7944ce9ec.png)
it's already looking promising!

**Comment by SamuelSHrk** [comment]
YES THE MAPPING WORKS!

**Comment by SamuelSHrk** [comment]
OK on FL Studio, it detected I had an MPD218 but instead of YES i hit ALWAYS. But its not detecting any MIDI input

**Comment by SamuelSHrk** [comment]
> Hi @SamuelSHrk, I forgot to update this thread, sorry 'bout that! Yes, in fact, here's a preview for the upcoming v0.5.0 release, and it has a built-in MIDI controller preset for the MPD218.
> 
> https://drive.google.com/file/d/1AcYp8iDgynxLN3A8r_0zAkWl2VyQdJ1J/view?usp=share_link
> 
> If everything works OK, VMPC2000XL should detect it when you hook up an MPD218 and ask you if you want to switch to that mapping. To actually see and tweak the mapping, you can go to VMPC settings (Shift + 0) and then the MIDI tab (F5).

It shows the pads are all at ch 10, while when I used the learning mode, the MPD pad indicated a ch 1, presumably MIDI channel 1

**Comment by izzyreal** [comment]
Looks like FL Studio internally transforms the MIDI input coming from the MPD218 from channel 10 to channel 1. I don't see an obvious way to let FL Studio not transform the channel.

What you can do for now in the MIDI tab is set the channels for each mapping to "all":
<img width="512" alt="image" src="https://user-images.githubusercontent.com/3707432/206841124-7939218c-8ad2-4770-adda-25679bf4e4a7.png">

Once you have changed all of them, you can save the MPD218 preset by pressing OPEN WINDOW (or "i" on your keyboard) to open the "MIDI controller presets" window and overwrite the original MPD218 preset:

<img width="513" alt="image" src="https://user-images.githubusercontent.com/3707432/206841195-04dd29c1-4076-4a1c-b396-0428ca4294a3.png">

**Comment by izzyreal** [comment]
I've noticed the "ALWAYS" functionality does not pick up correctly if you have already connected the MDP218 _before_ launching VMPC2000XL. This is a bug that I will address here: https://github.com/izzyreal/mpc/issues/121

For now you can workaround this by starting VMPC2000XL without the MPD218 connected.

**Comment by SamuelSHrk** [comment]
> Looks like FL Studio internally transforms the MIDI input coming from the MPD218 from channel 10 to channel 1. I don't see an obvious way to let FL Studio not transform the channel.
> 
> What you can do for now in the MIDI tab is set the channels for each mapping to "all": <img alt="image" width="512" src="https://user-images.githubusercontent.com/3707432/206841124-7939218c-8ad2-4770-adda-25679bf4e4a7.png">
> 
> Once you have changed all of them, you can save the MPD218 preset by pressing OPEN WINDOW (or "i" on your keyboard) to open the "MIDI controller presets" window and overwrite the original MPD218 preset:
> 
> <img alt="image" width="513" src="https://user-images.githubusercontent.com/3707432/206841195-04dd29c1-4076-4a1c-b396-0428ca4294a3.png">

awesome, i did what you said and now all the pads work. Unrelated issue but i wished the window size was the same each time It was booted up on FL. Other than that, all the pads on the MPD218 match with the VMPC pad orientation.

**Comment by izzyreal** [comment]
https://izmar.nl/release-candidates First release candidate for v0.5.0 is available. Please check it out when you have time. It comes with the MPD218 preset, and any FL projects that already have VMPC2000XL should retain the window size. For new VMPC2000XL plugin instances, the default window size of 649x497 is used.

Let me know if we can close this issue.

**Comment by SamuelSHrk** [comment]
@izzyreal I haven't used it yet but I download the installer for it yesterday. When I get home I will see if everything is lined up. If there is no issue, then this thread can be closed.

**Comment by izzyreal** [comment]
Awesome, thanks in advance @SamuelSHrk

**Comment by SamuelSHrk** [comment]
> Awesome, thanks in advance @SamuelSHrk

midi still messed up. i booted it up and it doesnt detect any input from the MPD218 pads strangely. I still had to correct them iun the MIDI Learn section by changing the MIDI channel for each note to 1.

**Comment by izzyreal** [comment]
> > Awesome, thanks in advance @SamuelSHrk
> 
> midi still messed up. i booted it up and it doesnt detect any input from the MPD218 pads strangely. I still had to correct them iun the MIDI Learn section by changing the MIDI channel for each note to 1.

I just realised I still had to update the bundled MPD218 preset so it defaults to receiving on all MIDI channels.

Please unzip this file and overwrite the existing `MPD218.vmp` in `~/Documents/VMPC2000XL/MidiControlPresets` with this one. Then try again and it should work fine in standalone and in FL.

[MPD218.vmp.zip](https://github.com/izzyreal/mpc/files/10682700/MPD218.vmp.zip)

**Comment by SamuelSHrk** [comment]
@izzyreal it did indeed work and had no issues whatsoever with it. 
Only thing that bugs me left is default window size and maybe text highlights over the number buttons since the text is really small, but that's all a separate issue I might create.

**Comment by izzyreal** [comment]
Great news! I'll close the ticket after I've integrated the required changes in the code.

I'll have think a bit about the window size issue. Please go ahead and create a ticket for that.

For text labels on the case being too small, also please create a ticket.

**Comment by izzyreal** [comment]
Resolved in f4e7d3625fbee2aa783f3b0f6054f67eea9a6622
