### ISSUE TITLE
Crash upon bank switch

### ISSUE THREAD

**Issue by izzyreal** [izzyreal/mpc#142]
Reported by Daniel via email:

"I had a sample on Bank B and wanted to set the individual out for this one and suddenly there was no sound anymore on any bank. I reloaded the samples and on Bank A then the sound was working again but as soon as I switched to bank B the app crashed."

Also see the attached crash report.

[20230319_crash.txt](https://github.com/izzyreal/mpc/files/11048513/20230319_crash.txt)

**Comment by izzyreal** [comment]
@messeraffe I can't reproduce this one based on the info you gave. Do you know how to reproduce it?

**Comment by messeraffe** [comment]
@izzyreal Ah yes, sorry. I meant Drum Program 2. This menu doesn´t exist in the MPC 2000. 
<img width="534" alt="image" src="https://user-images.githubusercontent.com/111270880/227349648-1e1bd896-e535-4065-8e12-0214c8fa679e.png">
Shift 7, then Press F2, and then try to change the individual out. I guess the bank does not matter. It just crashed again for me

**Comment by izzyreal** [comment]
@messeraffe

Easiest would be if you make a numbered, complete list of reproduction steps, like
1. Start VMPC
2. Load a sample onto pad 1
3. etc.

so we work with exactly the same actions.

**Comment by izzyreal** [comment]
@messeraffe I think the issue should be fixed now. Please try with this:
https://drive.google.com/file/d/1BQdYE4kFwoHMbJu9J_lifasdz1UskZwM/view?usp=sharing

**Comment by izzyreal** [comment]
@messeraffe I was able to confirm similar issues on my end and have fixed it. Can you try this one please?https://drive.google.com/file/d/1-IWZrNa5LFmH5ZjVQTkT99fWhF_rOpA5/view?usp=sharing

**Comment by messeraffe** [comment]
@izzyreal I can´t seem to download it
<img width="400" alt="image" src="https://user-images.githubusercontent.com/111270880/227720542-a00a649b-9ea8-4731-a477-4b5da09c9b3a.png">

**Comment by izzyreal** [comment]
@messeraffe Sorry, I just updated it: https://drive.google.com/file/d/17rHPLvzjH3q6qfyp3vmA7JyaLia09E0F/view?usp=sharing

**Comment by messeraffe** [comment]
@izzyreal It´s working fine now. Thanks!
