### ISSUE TITLE
Note events are skipped during play after moving them in step editor

### ISSUE THREAD

**Issue by izzyreal** [izzyreal/mpc#143]
Reported by Daniel via email:

"A note that I moved one tick earlier in the step editor is skipped during play. It is also skipped when using the locate + next function but is found when either using locate + previous or moving forward one tick at a time. I hope this video helps to explain it (unfortunately the sounds did not get recorded).

You can reproduce it by moving the event at 002.04.83 in the attached .ALL file one tick earlier."

https://user-images.githubusercontent.com/3707432/227146616-8b7489cb-731b-4e70-accc-0c0f741da0b7.mov

[ALL_SEQ_SONG1.ALL.zip](https://github.com/izzyreal/mpc/files/11048578/ALL_SEQ_SONG1.ALL.zip)

**Comment by messeraffe** [comment]
I got a similar issue again. Very hard to reproduce. The note was not picked up when running the sequencer and in step edit mode I could not add additional notes on top of the affected event. Will have to test further and keep you posted.

**Comment by izzyreal** [comment]
Did you get it again with the latest version I posted this morning [here](https://github.com/izzyreal/mpc/issues/142#issuecomment-1483773651) or a previous one?

When you say "moved one tick earlier", do you mean you COPY and DELETE the event, then you navigate 1 tick ahead and do PASTE?

Can you provide the APS for the attached ALL file?

**Comment by messeraffe** [comment]
I got it on a previous version. I can´t download the new version yet. 
Just retested it in the AU version and it´s still behaving the same

> When you say "moved one tick earlier", do you mean you COPY and DELETE the event, then you navigate 1 tick ahead and 
> do PASTE?
Yes, but I guess by ahead you mean 1 tick later (maybe it´s my English though) but in my case I moved the event from 002.04.83 -> 002.04.82 (earlier in time)

Please find the APS attached.
[ALL_PGMS.APS.zip](https://github.com/izzyreal/mpc/files/11069045/ALL_PGMS.APS.zip)

**Comment by messeraffe** [comment]
Is there a way to get the exact version of the AU plugin? The UI 0.5.0.3 but as I can´t delete the AU file (or don´t know where it is) I´m not sure whether it gets installed properly with every update.

**Comment by izzyreal** [comment]
> Please find the APS attached. [ALL_PGMS.APS.zip](https://github.com/izzyreal/mpc/files/11069045/ALL_PGMS.APS.zip)
Can you send one with sounds?

**Comment by izzyreal** [comment]
> Is there a way to get the exact version of the AU plugin? The UI says 0.5.0.3 but as I can´t delete the AU file (or don´t know where it is) I´m not sure whether it gets installed properly with every update.

The installation directory for the AUv2 is `/Library/Audio/Plug-Ins/Components`. As far as I know that is where it is always installed, but you can also check `~/Library/Audio/Plug-Ins/Components`. The AUv3 is embedded in the `.app` file.

**Comment by izzyreal** [comment]
I was able to reproduce it with the older version, and I can confirm that it's fixed in the newer version I gave you ([this commit](95e47078a48dbc3da93ca7266a92bb8f727233ac)).

If you still have the older version around you can try these reproduction steps:
1. Sequence of 1 bar
2. Hihats on every 16th
3. Snare on 001.01.95
4. COPY and DELETE the snare
5. Move to 001.02.00
6. PASTE the snare
7. Play the sequence
8. Observe that the snare is played at the start of the sequence, and not at 001.02.00.

**Comment by messeraffe** [comment]
> > Please find the APS attached. [ALL_PGMS.APS.zip](https://github.com/izzyreal/mpc/files/11069045/ALL_PGMS.APS.zip)
> 
> Can you attach one with sounds?

Actually I saved it with sounds. I haven´t worked with APS before: are they kept separate or are they usually integrated into the APS file? Anyhow, here are the sound files of the program:
[sounds.zip](https://github.com/izzyreal/mpc/files/11069208/sounds.zip)

**Comment by messeraffe** [comment]
> ~/Library/Audio/Plug-Ins/Components

Ah thanks, it was in `/Library/Audio/Plug-Ins/Components`, seems like when I navigate via Finder it goes to `~/Library/Audio/Plug-Ins/Components`. Now it´s deleted

**Comment by messeraffe** [comment]
> I was able to reproduce it with the older version, and I can confirm that it's fixed in the newer version I gave you ([this 
> commit](https://github.com/izzyreal/mpc/issues/95e47078a48dbc3da93ca7266a92bb8f727233ac)).

It´s working fine now. Thanks!

**Comment by izzyreal** [comment]
Great, I'll close the issue. Feel free to reopen it if you encounter the problem again.
