### ISSUE TITLE
Return to latest field position in step sequencer 

### ISSUE THREAD

**Issue by messeraffe** [izzyreal/mpc#144]
Not a bug but rather an enhancement, maybe through a global setting. 
Would be great if the step sequencer could store and return the latest field position whenever the user goes back to make changes. When using the decay modulation I find myself often going back to the step sequencer to adjust the velocity in order to change sample start but the curser always remains on the note field.

**Comment by izzyreal** [comment]
Sounds cool, but we'll need to work out the complete behaviour. When the Step Editor screen is opened, it has no idea what it will find. The user may have performed all kinds of mutations (record or erase events) to the sequence and in the UI (change active sequence or track) compared to the previous user visit.

Maybe we could remember at which tick from which track and which sequence the user last was, which event types where at that tick at the time, and if all these conditions have remained the same, we could let the Step Editor return its focus to the same field.

What do you think?

**Comment by messeraffe** [comment]
Ending up at the same tick position might by tricky though. Or do you mean changing the fields while navigating through the steps?
The way I usually use it is: make some changes on the velocity to change the sample start, leave the step editor, play the sequence, listen if it is working musically and if not then jump back into the sequencer, find the same note and change the velocity again. Repeat :)
I think only storing the last edited field might be sufficient but not everybody would like this behaviour as it deviates from the regular behaviour in the hardware (I should test this by the way 🙂) but if it was configurable through the settings page I could imagine that it would be a huge time saver.

**Comment by izzyreal** [comment]
Resolved in a5cc55f6e1880710e6c34725efb1225cf9ed7087.
