### ISSUE TITLE
Change sample start/end via slider not working through midi

### ISSUE THREAD

**Issue by messeraffe** [izzyreal/mpc#147]
1. go to Trim screen
2. go to sample start or end
3. press shift and move the slider via mouse: sample start/end changes just fine
4. try this via midi and the screen goes to the Main Menu

**Comment by izzyreal** [comment]
Works fine on my end. Sounds like a MIDI mapping issue. What do you have here?
<img width="373" alt="image" src="https://user-images.githubusercontent.com/3707432/227788293-a5505e74-47eb-44f9-98f8-a7f615738c58.png">

**Comment by messeraffe** [comment]
Thanks for the hint. Seems like I somehow mapped the same CC number to two functions. After I turned the other one to "off" it´s now working fine.
