### ISSUE TITLE
Play button not triggered via midi

### ISSUE THREAD

**Issue by messeraffe** [izzyreal/mpc#149]
Regular play button is not reacting for via midi on AKAI MPD32

**Comment by izzyreal** [comment]
This too seems like a MIDI mapping issue. For me learning from a random CC or Note works fine here:
<img width="377" alt="image" src="https://user-images.githubusercontent.com/3707432/227788781-10dc8b87-93f3-48b6-b1e1-b5c78d5e3534.png">

**Comment by messeraffe** [comment]
Yes, the transport buttons are acting funny here. They are working in general so I just remapped them to navigate similar to the cursor buttons but VIM style :)
Thanks
