### ISSUE TITLE
Record & Overdub button not working properly via midi

### ISSUE THREAD

**Issue by messeraffe** [izzyreal/mpc#150]
When pressing record or overdub via Midi the respective mode is activated permanently and not toggled in combination with the play buttons. I can even set both at the same time which I think is not possible on the hardware:
<img width="421" alt="image" src="https://user-images.githubusercontent.com/111270880/227773845-9da3897a-9652-4679-b491-8b0aa369c95a.png">

In addition I can not unarm the record or overdub mode when pressing the buttons again. Also pressing stop does not deactivate them.

**Comment by izzyreal** [comment]
This too works fine on my end. I tried it with all kinds of controllers: toggle, pot, slider, pads and rotary encoder. For some of them you have to move all the way down to value 0 before the OVERDUB led goes off again.

**Comment by messeraffe** [comment]
I´m using the transport buttons on the MPD32

<img width="539" alt="image" src="https://user-images.githubusercontent.com/111270880/227792049-ece0063f-6b45-486a-8eda-eef80d06663b.png">

They can send MMC/MIDI or CTRL so I guess they are causing the issue as the mapping should be fine this time
<img width="418" alt="image" src="https://user-images.githubusercontent.com/111270880/227791985-802d09a2-ce99-4335-be40-126e26e9b971.png">

**Comment by messeraffe** [comment]
Yes, with other buttons or knob it´s working fine so it must be the transport buttons. They are working in general so I just remapped them to navigate similar to the cursor buttons but VIM style :)
Thanks

**Comment by izzyreal** [comment]
@messeraffe Can you let me know what the MPD32 sends exactly when you press, and when you release the transport button?

**Comment by messeraffe** [comment]
![IMG_EDAECCFB8D1A-1](https://user-images.githubusercontent.com/111270880/227802796-2c59b312-bcc6-4cba-a16b-fbdeece4d3c0.jpeg)

CC 118 is play. It send these clock events. Then I found in the global settings that the clock was set to internal. Maybe this was causing the issues?

**Comment by izzyreal** [comment]
Letting the MPD32 transmit MIDI clock may or may not affect VMPC2000XL. VMPC2000XL should ignore all MIDI clock messages if you change this setting to OFF:
<img width="423" alt="image" src="https://user-images.githubusercontent.com/3707432/227884156-2eeaa118-5a70-4ef3-9390-85e8fc466bf4.png">

But for initial testing indeed I'd disable MIDI clock transmission on the MPD32 altogether.

**Comment by messeraffe** [comment]
No, nothing is sent on release
