### ISSUE TITLE
Full screen mode for detached screen on iOS

### ISSUE THREAD

**Issue by messeraffe** [izzyreal/mpc#154]
When the user double taps on the screen a second movable copy of the screen is opened. Would it be possible so set this on full screen for users who work with an external keyboard or midi controller (especially on the iPhone this would be helpful because of the smaller screen)

**Comment by messeraffe** [comment]
I just saw that the second screen actually is resizable...

**Comment by izzyreal** [comment]
How far does it go?

**Comment by izzyreal** [comment]
I've added a maximize button and bumped the maximum size in https://github.com/izzyreal/vmpc-juce/commit/8a6eb0602839feedd19027f06fa628835fa6f04b. Feel free to reopen if you need anything else.
