### ISSUE TITLE
Change sample start/end via slider not working in Zone screen

### ISSUE THREAD

**Issue by messeraffe** [izzyreal/mpc#169]
1. go to Trim screen
2. go to sample start/end
3. press shift and move the slider: sample start/end changes just fine
4. go to Zone screen
5. press shift and move the slider: sample start/end doesn´t change

@izzyreal I can´t verify whether this is a bug because the 2K doesn´t even have this feature but I would assume this should work in all screens?

**Comment by izzyreal** [comment]
According to [the manual](https://www.platinumaudiolab.com/free_stuff/manuals/Akai/akai_mpc2000xl_manual.pdf) it is not available for ZONE. It's mentioned explicitly for TRIM and LOOP, for example "You can also use the NOTE VARIATION slider while holding the SHIFT key."

Doesn't mean we can't add it to VMPC2000XL. Only question is how to translate the slider's 0-127 range. I'll take a look at the logic used for determining the lower and upper bounds when moving a zone's St or End, and then use `upper bound` - `lower bound` to map the slider's 0-127 range to frame indices.

**Comment by messeraffe** [comment]
Thanks for clarifying. Luckily the Shift+Cursor feature is still working here otherwise the rotation would take too long, even when using 2 fingers on iOS.

**Comment by izzyreal** [comment]
Finally picked up this issue, and the real 2KXL lets you use the slider to in the ZONE screen change start and end.

It actually also lets you select zone and PLAY X mode with te slider too :) I might add that.

But more importantly, in any of the "fine" screens (zoomed waveform view) the slider should also work. So I'll first implement this and the zone slider support.

**Comment by izzyreal** [comment]
This will be part of the v0.5.8 release which I plan to do in the near future.
