### ISSUE TITLE
Typing with pads or buttons is not possible on iOS

### ISSUE THREAD

**Issue by messeraffe** [izzyreal/mpc#170]
On iOS when trying to rename a program or sample the pads and buttons (numbers, space) have no effect.

**Comment by izzyreal** [comment]
It's currently unimplemented on any platform. Thanks for the reminder, will add this.

**Comment by izzyreal** [comment]
Resolved in ae05c2ad8ae4611a2dd63fb3ea3af06eb73cc60c.
