### ISSUE TITLE
[real mpc2000xl] What is the exact behaviour of UNDO SEQ?

### ISSUE THREAD

**Issue by izzyreal** [izzyreal/mpc#186]
In which cases is the undo buffer retained, and in which cases is it flushed?

The manual states:
```
You can only use the UNDO SEQ key when you
are recording or editing a sequence. You cannot
use this key when you are editing a program or
sound. Using the UNDO SEQ is also limited to the
time just after a recording or edit. If you move to
another mode or function screen, the UNDO SEQ
mode will be disabled.
```

but it's not a very accurate description and there may be exceptions.

Some questions that come to mind:
1. Let's say we have just recorded some notes in the MAIN screen while the sequencer was running. The UNDO SEQ light is now on. Does it go off if we change the tempo?
2. Let's say we have just recorded some notes in the MAIN screen while the sequencer was running. The UNDO SEQ light is now on. Now we go to the step editor, and back to the MAIN screen. Is the UNDO SEQ light still on? Can we still undo to the state right before recording some notes in the MAIN screen?

**Comment by izzyreal** [comment]
@messeraffe Since I'm not close to a real MPC2000XL at the moment, do you happen to know are are you willing to find out how UNDO SEQ behaves exactly on the MPC2000?

**Comment by messeraffe** [comment]
@izzyreal changing the tempo does not affect the undo function but changing the sequence number or leaving to either to STEP or EDIT as well as any of the other screens that can be reached via Shift will remove the undo light.
Once you navigate to STEP this is considered a new change even if you don't change anything in the step editor. So in 2.) the undo light will remain on but if you hit undo you are not undoing your live recorded notes but only the changes you did in the step editor.

**Comment by izzyreal** [comment]
@messeraffe Thanks for checking so quickly 😄 That's pretty much what I was expecting, nice one

> Once you navigate to STEP this is considered a new change

I suppose vica versa is also true? I.e. once you navigate from STEP to MAIN the undo buffer is flushed?

What about _within_ STEP? If you navigate to another position, is the undo buffer retained or flushed?

Moreover I'm expecting that if you go into STEP editor, go to a tick position that already had a note from recording in MAIN, delete that note, and you press UNDO, the note will appear again without having to perform any other actions. Can you confirm?

**Comment by messeraffe** [comment]
@izzyreal think of entering + leaving Step edit as it´s own possibleundo block. Whatever happens inside step edit, remains in step edit ;)

If you start completely from scratch and the only thing you do is enter and leave step edit the UNDO SEQ light will be on.

> Moreover I'm expecting that if you go into STEP editor, go to a tick position that already had a note from recording in > > >MAIN, delete that note, and you press UNDO, the note will appear again without having to perform any other actions. Can >you confirm?
yes, correct

**Comment by messeraffe** [comment]
> What about within STEP? If you navigate to another position, is the undo buffer retained or flushed?
It depends on how you define it. Everything before you entered step edit is flushed. All changes within step edit are retained and can be collectively "undone".

**Comment by izzyreal** [comment]
>  All changes within step edit are retained and can be collectively "undone" once you exit step edit.

That's what I meant, thanks again for confirming

**Comment by izzyreal** [comment]
Implemented in https://github.com/izzyreal/mpc/issues/179 / a0ad7db99e32c1b1ee5ee59a69462c4312db9ba2
