### ISSUE TITLE
volume for each pad

### ISSUE THREAD

**Issue by jaybaby0713** [izzyreal/mpc#204]
how do you turn the volume down for each pad track

**Comment by izzyreal** [comment]
One way is via the mixer. Go to this screen by pressing Shift + 7, then F1:
<img width="401" alt="image" src="https://github.com/izzyreal/mpc/assets/3707432/308e4649-4ae1-4a99-903a-314e52c9de63">
Once you're in this screen, you can hit a pad to select it. Press arrow-down to move to the vertical fader part of the mixer strip and then turn the DATA wheel to change the volume for that specific pad.

**Comment by jaybaby0713** [comment]
THANK YOU SIR I REALLY APPRECIATE THAT I LOVE IT  GOOD WORK
    On Saturday, June 24, 2023 at 11:21:14 PM PDT, Izmar Verhage ***@***.***> wrote:  
 
 


One way is via the mixer. Go to this screen by pressing Shift + 7, then F1:

Once you're in this screen, you can hit a pad to select it. Press arrow-down to move to the vertical fader part of the mixer strip and then turn the DATA wheel to change the volume for that specific pad.
