### ISSUE TITLE
layering 2 or more sounds on one pad

### ISSUE THREAD

**Issue by jaybaby0713** [izzyreal/mpc#205]
how do you layer sounds like put more than one on just one pad

**Comment by izzyreal** [comment]
You can't associate more than one sound with a pad. But you can let pads trigger 1 or 2 other pads.

Press Shift + 6 to go to the ASSIGN screen. Hit the pad that you want to let trigger other pads. Set the `Mode:` to `SIMULT`:
<img width="406" alt="image" src="https://github.com/izzyreal/mpc/assets/3707432/e1dbc37d-8709-4033-a1dc-70bc09ff3de2">
Then in the right-hand side in one of the `Also play note:` fields select the note/pad that should be triggered simultaneously.

**Comment by jaybaby0713** [comment]
yes sir i see what your saying pretty cool
