### ISSUE TITLE
record/overdub button

### ISSUE THREAD

**Issue by jaybaby0713** [izzyreal/mpc#206]
do you have to hold the record/overdub button and press play from the vmpc or can you just tap the record/overdub button on  [without holding] and hit the play button on fl studio

**Comment by izzyreal** [comment]
You'll have to press both. It's a bit too tricky, still looking for a way to improve it, but you can for example hold rec with the mouse and press space to play or backslash to play from start. You can also hold L for record and backslash for play from start.

**Comment by jaybaby0713** [comment]
yeah that is a bit tricky i held overdub and press play on fl studio and the vmpc at the same time and it worked...I hope you can fix that one soon but overall i love it its a great piece to have in my studio thanks for making this sir...... how do you get the play and record buttons to work on the mpc element pad controller to master control it with the pad controller

**Comment by izzyreal** [comment]
> how do you get the play and record buttons to work on the mpc element pad controller to master control it with the pad controller

@jaybaby0713 Check out https://vmpcdocs.izmar.nl/vmpc_specific_settings.html#midi-control

Let me know if the documentation is not clear enough! In some places it's too technical, in other places it doesn't give enough info, so it's a work in progress and your feedback would be highly appreciated 😄 

Cheers for now
