### ISSUE TITLE
THE OVERDUB/PLAY ISSUE

### ISSUE THREAD

**Issue by jaybaby0713** [izzyreal/mpc#207]
ARE THEIR ANY FIXES TO THE OVERDUB/PLAY BUTTON TO WHERE YOU CAN JUST TAP OVERDUB AND PRESS PLAY FROM FL STUDIO

**Comment by izzyreal** [comment]
Hi @jaybaby0713, not yet, I'll give it some thought.

What kind of fix do you have in mind exactly? You want VMPC2000XL to start recording when you press the record button in FL Studio?

**Comment by jaybaby0713** [comment]
I WAS SEEING IF YOU HAD A FIX TO WHERE YOU CAN JUST TAP OVERDUB OR HOLD OVERDUB AND PRESS PLAY FROM FL STUDIO INSTEAD OF YOU HAVING TO PRESS PLAY/OVERDUB ON FL AND VMPC AT THE SAME TIME TO RECORD ON VMPC

**Comment by izzyreal** [comment]
Keep an eye out on this issue. I'll look into it in the near future and post updates here. For now, I recommend to use the keyboard controls: https://vmpcdocs.izmar.nl/controls.html#basic-operations

**Comment by jaybaby0713** [comment]
THANKS

**Comment by izzyreal** [comment]
In https://github.com/izzyreal/mpc/issues/209 you suggested something like locking the OVERDUB or REC button, if I understood you correctly.

I think that might actually work, but there's a few details to cover:
1. How does the user lock OVERDUB/REC? I was thinking press and hold for more than 2 seconds, or double-clicking.
2. How does the user unlock OVERDUB/REC? Some quick ideas that come to mind are:
- The moment you press any other button, but if it's PLAY/PLAY START that you pressed, it will respect the locked state of the OVERDUB/REC button and start overdubbing or recording.
- The moment you press the locked button again, it unlocks.

What do you think?

By the way, it would be great if you wouldn't use all caps.

**Comment by jaybaby0713** [comment]
im sorry for the caps sir i was just separating the main words thats on the mpc but all i know is that you have to press play on fl studio overdub button and play on the vmpc all at the same time for it to work its kind of tricky it messes with the work flow when i have to press 3 buttons all at the same time and sometime i have to keep trying ....can you fix it to where you turn overdub red button on and just press play on fl studio.... its not staying on record when i press play on fl studio....overdub and record turns off once you press play on fl studio

**Comment by izzyreal** [comment]
For recording and overdubbing in VMPC2000XL, you don't need 3 buttons at the same time. You need 2.

Have you looked at [the keyboard shortcuts](https://vmpcdocs.izmar.nl/controls.html#basic-operations) and tried them out?

Make sure that the VMPC2000XL plugin is open and focused. Then press and hold `L` while pressing either `space-bar` or `\`.

This works fine in FL Studio 21 on macOS with VMPC2000XL v0.5. Can you confirm it works for you as well?

**Comment by jaybaby0713** [comment]
ok thanks sir i will post and confirm soon as i get in the studio and i have fl studio 20 on windows 7/32 bit.... is it any difference from your fl studio 21 being on mac

**Comment by jaybaby0713** [comment]
its not working....i still have to press play and record on the vmpc and press play on the fl studio all at the same time....all 3....can you set it to where  you press and hold L while pressing either space-bar or \......i have windows 7 32/64 bit.....its like...when i press play on fl studio while holding the record button the record button turns off...

**Comment by izzyreal** [comment]
Strange 🤔 In some cases FL Studio might pause processing of plugins to optimize CPU usage. That would produce the result you're describing. To disable this behaviour, can you make sure the "Smart disable" option is inactive, like shown below?
<img width="511" alt="image" src="https://github.com/izzyreal/mpc/assets/3707432/8b14a4ab-8bf9-402f-8649-3940f8b4cb3d">

**Comment by jaybaby0713** [comment]
ok ...the only thing that changed was that i can press play on fl studio and then wait 2 seconds and then press and hold L then press spacebar for the vmpc to work.....is that the way it suppose to work?

**Comment by izzyreal** [comment]
The idea is that you won't have to press play in FL Studio at all.

Are you able to play a sequence in VMPC2000XL when FL Studio is not playing? If you're in an initialized sequence, meaning  the name of the sequence has changed from "(Unused)" to for example "Sequence01", and you press PLAY or hit the spacebar, the "001.01.00" time display in the top-right of VMPC2000XL's LCD screen should start counting.

**Comment by jaybaby0713** [comment]
yes sir im able to play a sequence when fl studio is not playing, and yes i initialized a sequence to "sequence01" and then i hit the spacebar but fl studio didnt start up, the only thing started playing was the vmpc....so your saying when i hit play on the vmpc the flstudio should start playin also?

**Comment by izzyreal** [comment]
Only VMPC2000XL should start playing. Checking that the time display is counting is a way to verify that the plugin is indeed getting processed by FL Studio.

Ok, so let me know how these steps work out for you:
1. Hit space and VMPC2000XL starts playing (time display is counting).
2. Click the stop button with the mouse.
3. Press `L` + `\` simultaneously on your keyboard. Now you should hear VMPC2000XL's click track and see the time display start counting. FL Studio does not start playing/recording.

**Comment by izzyreal** [comment]
By the way, there are ways to synchronize VMPC2000XL with the DAW, as either a master or a slave. I'm now thinking that this may be what you've asking about all this time 😅 Let me know if that's the case.

**Comment by jaybaby0713** [comment]
how do you use it (vmpc) as a master in fl studio and get fl studio to start too

**Comment by izzyreal** [comment]
I've only managed to slave sync Ableton Live with VMPC2000XL as a master.

The most natural way is indeed that FL Studio would be the master, and that you would somehow be able to start recording in VMPC2000XL by pressing FL Studio's play button. There's currently no way to do this.

I'm finally starting to understand your problem, sorry for taking so long. I think locking the REC button, as mentioned [here](https://github.com/izzyreal/mpc/issues/207#issuecomment-1665110981), would solve it. What do you think?

**Comment by jaybaby0713** [comment]
yes holding the overdub/rec button for 2 seconds to turn record button light on red would be great then you wont have to press both play/rec on vmpc at the same time that way when you press play on fl studio, the vmpc is in record mode alrealdy.....how long will it take for you to do it?

**Comment by jaybaby0713** [comment]
yes what you had mentioned in your message a day or 2 ago is the best way

1.How does the user lock OVERDUB/REC? I was thinking press and hold for more than 2 seconds, or double-clicking.
2.How does the user unlock OVERDUB/REC? Some quick ideas that come to mind are:
The moment you press any button, it unlocks. But if it's PLAY/PLAY START that you pressed, it will respect the locked state of the OVERDUB/REC button and start overdubbing or recording.
The moment you press the locked button again, it unlocks.
What do you think?

**Comment by izzyreal** [comment]
@jaybaby0713 Here's an **experimental** v0.5.1.1 https://drive.google.com/file/d/1pq01vRZhRSHkjC1pLF4rFXsW_oCxgmQ0/view?usp=drive_link

It offers 3 ways to lock REC or OVERDUB:

1. Double-click it with the mouse to lock.
2. Click and hold it for 2 seconds.
3. Press its keyboard key for 2 seconds (`L` for REC or `;` for OVERDUB).

To unlock, click or press REC or OVERDUB as usual.

I think the double-click variety can make it into the mainline VMPC2000XL release soon.

But click-and-hold is a bit trickier to put in the mainline release, because holding REC or OVERDUB is already a valid action in the original MPC2000XL. It allows you to record or overdub in stop mode. Those who make use of this flow will be unpleasantly surprised to find out that all of a sudden REC or OVERDUB is locked after holding them and entering a few notes.

So I hope that the double-click action with the mouse works well for you. Let me know how it goes!

**Comment by jaybaby0713** [comment]
that is AWESOME!!! my friend i like number 2 the best and number 1 is great also... number 3 is ok... You really did a good job i love what you did for this great machine you are a genius my friend cant wait to see more of your great work that was just what i was talking about....i will message you if i need some more help my friend thanks again

**Comment by izzyreal** [comment]
Resolved in 89dacff011847a5182056656004670956ddb7aac and https://github.com/izzyreal/vmpc-juce/commit/bae42d57084ff25dc2377b8e7a64fa4bb2769c1c.

Note that for now I'll only push the double-click way to lock REC or OVERDUB to the stable release, so when v0.5.2 comes out and you install it, you won't be able to use the press-and-hold-for-2-seconds way that I put in the v0.5.1.1 experimental release I gave you.

I'll have to think a bit more about the press-and-hold-for-2-seconds way to know if we can add it to the stable release because of the reservations mentioned earlier:

> holding REC or OVERDUB is already a valid action in the original MPC2000XL. It allows you to record or overdub in stop mode. Those who make use of this flow will be unpleasantly surprised to find out that all of a sudden REC or OVERDUB is locked after holding them and entering a few notes.

**Comment by jaybaby0713** [comment]
okay thanks alot for creating that version for me sir. it helps me out alot
