### ISSUE TITLE
overdub/play  FIX

### ISSUE THREAD

**Issue by jaybaby0713** [izzyreal/mpc#209]
ARE THEIR ANY FIXES TO THE OVERDUB/PLAY BUTTON TO WHERE YOU CAN JUST TURN THE OVERDUB ON RED AND PRESS PLAY FOR BOTH BUTTONS TO RECORD FROM FL STUDIO

**Comment by izzyreal** [comment]
I'll move this to https://github.com/izzyreal/mpc/issues/209 if you don't mind.
