### ISSUE TITLE
Step editor ignores duration of notes with looped samples

### ISSUE THREAD

**Issue by c3ntr0n800** [izzyreal/mpc#213]
I was experimenting with looping samples of synths, and I noticed a really strange issue with playing them in the step editor: Any value you set for the duration of a note assigned with a looped sample will be ignored, and it will endlessly play it until you turn off the looping for the sample in Trim mode.

**Comment by c3ntr0n800** [comment]
Alright I revisited to see if there's some sort of workaround, and I have found the issue:

In the **Parameter** window in **Program**, the note with the looped sample is supposedly set to _Note Off_. However, when you turn off the loop of the sample in **Trim**, the parameter for it is actually set to _Poly_. 

Changing it to Note Off and then re-enabling the loop in **Trim** will fix this bug.

**Comment by izzyreal** [comment]
Nice find. Lemme dig.

**Comment by izzyreal** [comment]
@c3ntr0n800 Which OS are you on? I'll send you a preview build to test.

**Comment by c3ntr0n800** [comment]
@izzyreal Currently I'm using Windows 10.

**Comment by izzyreal** [comment]
@c3ntr0n800 https://drive.google.com/file/d/1YydHbYC40W0s6bSqvZOu21acP-hx5snk/view?usp=sharing

**Comment by izzyreal** [comment]
Supercool, many thanks for reporting, testing and confirming. I'll push an official v0.5.6 release today.

Resolved in b4fa8e5c86ca69331219c86c66e0be6004589320
