### ISSUE TITLE
Channel Settings : Stereo mode Bug

### ISSUE THREAD

**Issue by pfortythree** [izzyreal/mpc#238]
On both - Windows 10 (22H2) (19045.4412) in vMPC2000XL v.0.6.0 (standalone and in VST in Ableton 11 (last update) ) and on iPadOS 17.5.1 vMPC2000XL v.0.6.0 on iPad Pro (4Gen) the same issue:
1) Starting app
2) Go to MIXER
3)Try to assign individual outputs for 8 MONO out (1,2,3,4 etc.)
4)Only MIXED OUTs available (1\2, 3\4, etc)

**Comment by izzyreal** [comment]
Thanks for the report and resolution @pfortythree

**Comment by pfortythree** [comment]
It resolves my problem, but parameter in “follow stereo:” seems to be
bugged anyway - it studied and doesn’t changing after that

Пн, 24 июня 2024 г. в 19:58, Izmar Verhage ***@***.***>:

**Comment by izzyreal** [comment]
> It resolves my problem, but parameter in “follow stereo:” seems to be bugged anyway - it studied and doesn’t changing after that Пн, 24 июня 2024 г. в 19:58, Izmar Verhage ***@***.***>:

If that's reproducible, could you create an issue for that with steps to reproduce?
