### ISSUE TITLE
Error in names of PAN settings in mixer 

### ISSUE THREAD

**Issue by pfortythree** [izzyreal/mpc#241]
This occurs both  iPadOS and Windows v.0.6.0 in Standalone, AUv3 and VST versions
1)Open mixer
2)Choose advanced Channel Settings by pressing "Open Window" button
3)Change "Pan:" menu from full R side (displays R100) to full L side (displays MID)
But I think it should be displayed L50 for full L Side and R50 for full R side and MID is for Centered panorama option

https://github.com/izzyreal/mpc/assets/173607089/1299ed3f-6700-4547-a715-cc84794331ae

**Comment by izzyreal** [comment]
Good find! Resolved in 40d8e31. I hope to publish a new release very soon.

**Comment by izzyreal** [comment]
Fix is part of https://github.com/izzyreal/vmpc-juce/releases/tag/v0.6.4, just released today.
