### ISSUE TITLE
crashing when loading .APS on mac OS X 

### ISSUE THREAD

**Issue by pajzd** [izzyreal/mpc#43]
i downloaded latest pkg without removing vMPC ? thought it was okay ... 
maybe i should reinstall everything ... also using .APS & planning on using  earlier
saved .ALL with this new download ... 

1. open vMPC
2. audio / midi settings - MOTU interface
MIDI in & out : Hercules midi port
3. click in the MPC screen, shift + 3 load, all files, 
[vmpc.log](https://github.com/izzyreal/mpc/files/4541010/vmpc.log)
navigate to right folder with .APS, click do it
4.  click on LOAD

Error report attached.
[error-report.txt](https://github.com/izzyreal/mpc/files/4543593/error-report.txt)

**Comment by pajzd** [comment]
Ok, so removed new version, clean install new version
didn't change audio midi settings, same crash while loading .APS file

Then i thought let's load a .ALL file & then .APS file ... 
.ALL worked, but .APS file let it crash ... 

reminder: both .APS & .ALL files were saved with previous version 

=> im about to install the earlier version, since it crashed, after a while
but not so fast :) so i could still make some progress

**Comment by izzyreal** [comment]
@pajzd The latest version is definitely way more stable, so use that.

Any APS or PGM files that you've created with older versions are to make even the new version crash, so you will need to remove them and start from scratch.

**Comment by pajzd** [comment]
ok understood ! installed last version

put samples in place, saved .all, saved .aps file
loaded .aps file
crashed while loading sample after very big big sample got loaded ...
is there sample time restriction maybe ?

[crash latest version vMPC.pdf](https://github.com/izzyreal/mpc/files/4544162/crash.latest.version.vMPC.pdf)
[vmpc.log](https://github.com/izzyreal/mpc/files/4544173/vmpc.log)

but i think i got it ... might be my drum samples r not 16 bit ... have to check 

frameSeq stop
A problem occurred when trying to load TSJAK_1_.WAV: Only 16 bit supported
A problem occurred when trying to load TSJAK_1_.WAV: Only 16 bit supported
A problem occurred when trying to load TSJAK_1_.WAV: Only 16 bit supported
A problem occurred when trying to load TSJAK_2_.WAV: Only 16 bit supported
A problem occurred when trying to load TSJAK_3_.WAV: Only 16 bit supported
A problem occurred when trying to load TSJAK_4_.WAV: Only 16 bit supported
A problem occurred when trying to load TSJAK_5_.WAV: Only 16 bit supported
frameSeq starting with sampleRate 44100.000000

**Comment by pajzd** [comment]
ok ! loaded all sounds, one midi sequence 
nothing saved 

then i run the sequence, put the metronome off
& jammed along with the pads & the sequenced sounds, beautiful !! for
a minute and half + - then unfortunately it crashed
but what a machine !!!! very enthousiastic about it
[vmpc.log](https://github.com/izzyreal/mpc/files/4544365/vmpc.log)

if i had the money , would defintely grab one 
but the thing is, since it has become old now ( ... oldschool hardware electronica )
having doubts ...

**Comment by izzyreal** [comment]
@pajzd Can you create individual tickets for any of the mentioned issues you need me to look into?
Also let me know if I can close this ticket. As far as I know loading a **valid** APS (created with real MPC2000XL or latest release of vMPC2000XL) works fine, please confirm.

**Comment by pajzd** [comment]
just tried again to load a new updated version .ALL file, crash
loading new saved .APS works !

[vmpc.log](https://github.com/izzyreal/mpc/files/4550480/vmpc.log)

**Comment by izzyreal** [comment]
Great that the APS file saving and loading works! I will close ticket.

Please create a ticket for the ALL file crash. Describe briefly how it was created and attach the failing ALL file to your ticket.
