### ISSUE TITLE
Vst hosting within standalone?

### ISSUE THREAD

**Issue by macpac512** [izzyreal/mpc#56]
Is it a feasible thing to allow the track type to include vsti plugins? I'm not sure how difficult that code would be to create/access.

**Comment by izzyreal** [comment]
Main problem would be that this breaks compatibility with the original, but I'm not entirely sure what you have mind.

**Comment by macpac512** [comment]
I understand the departure from the original,  but as an original MPC 60 user I was thinking forward. To me your app is more familiar than the new MPC standalone, and what they lack is vsti compatibility.  Only reasonSent from my Sprint Samsung Galaxy Phone.
-------- Original message --------From: Izmar Verhage <notifications@github.com> Date: 5/3/20  1:27 AM  (GMT-06:00) To: izzyreal/mpc <mpc@noreply.github.com> Cc: macpac512 <macpac412@gmail.com>, Author <author@noreply.github.com> Subject: Re: [izzyreal/mpc] Vst hosting within standalone? (#56) 
Main problem would be that this breaks compatibility with the original, but I'm not entirely sure what you have mind.

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/izzyreal/mpc/issues/56#issuecomment-623061921",
"url": "https://github.com/izzyreal/mpc/issues/56#issuecomment-623061921",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by izzyreal** [comment]
@macpac512 This feature is still on the table, but it's a big one and currently low priority as there are still too many bugs hampering ordinary, original functionality.

In the meantime we can refine this feature - think about the details of the implementation. Can you give a description of how you see this feature exactly? I'll bootstrap the discussion with the below.

You've mentioned track types. Real 2kxl has these track types: `MIDI`, `DRUM1`, `DRUM2`, `DRUM3` and `DRUM4`. You're thinking we add a `PLUGIN` or `VST3` track type? If yes, how does the user select which VST3i he/she wants to use for a track?

Or should there be one track type for each available VSTi?

**Comment by dromer** [comment]
Wouldn't it be easier to just have midi-out and control external plugins?

I'd say becoming a plugin-host is quite out of scope for this project, but maybe a V2 that takes the workflow and applies that to a plugin-host instead?

**Comment by izzyreal** [comment]
Closing this until a concrete description of the feature and its implementation exists.
