### ISSUE TITLE
Looped sample/note repeat bug

### ISSUE THREAD

**Issue by SxnnyB** [izzyreal/mpc#73]
Observed behaviour:
1. Using a looped sample
2. While in sequence playback or rec/overdub mode
3. Pressing note repeat
4. Pressing pad repeats note as expected
5. Releasing pad continues to play looped sample
6. Pressing stop on sequence stops looped sample

Expected behavior:
 In step 5. Looped sample should stop when pad is released.

**Comment by izzyreal** [comment]
Resolved by https://github.com/izzyreal/mpc/commit/b38d77640e5dddf86494a7628ee35da6735c9d47
