### ISSUE TITLE
Note repeat function toggle

### ISSUE THREAD

**Issue by SxnnyB** [izzyreal/mpc#74]
Observed behavior:
1. While in seq. playback or rec/overdub mode
2. Holding note repeat
2.1 missing display footer for note repeat mode
3. Pressing shift
4. Does not hold note repeat mode when note repeat button in released

Expected behavior.
2.1 should have display footer indicating note repeat function is active.

4. Pressing shift once while holding note repeat should hold note repeat function. As well as retain display footer to indicate note repeat function is active.

**Comment by izzyreal** [comment]
Resolved in https://github.com/izzyreal/mpc/commit/c6963b4dca1f56da72e97f22b9357a16da95b159 and the 2 subsequent commits.
