### ISSUE TITLE
16 levels erase all by any note

### ISSUE THREAD

**Issue by SxnnyB** [izzyreal/mpc#75]
Observed behavior:
1.16 levels note var tuning applied to pad
2. Recording sequence of various notes
3. While in rec/dub mode
4. Holding erase and any pad other than source pad will not erase notes.
5.only pressing source pad will erase notes

Expected behavior: 
4. While holding erase plus any pad in 16 levels should erase any 16 level notes for that time location.

Option opportunity:
This could be a user set feature that is toggled between accurate and improved mode where improved function allows you to erase specific 16 levels note by pressing that pad.

**Comment by izzyreal** [comment]
Resolved by 298a4a7b82af7ff73782508828304a41f13bf48a

**Comment by izzyreal** [comment]
This time the `accurate` and `improve` modes have been impemented hopefully as you intended: c312fb12e215248c7f3e22d808c6f32df6eb79bb

The 16 levels erase modes in the vmpc-settings screen are now "All levels" and "Only pressed level".
