### ISSUE TITLE
Note repeat temp muting other pads

### ISSUE THREAD

**Issue by SxnnyB** [izzyreal/mpc#77]
Observed:
1.Recorded snare and kick patterns
2. While still recording in dub mode
3. Shift+note repeat to hold mode
4. Holding hi hat pad past end of sequence
5. All other recorded notes stop triggering while hat is still being note repeated
6. Once sequence loops after repeated pad is released other pads come back.

Expected.
5. All other previously recorded data should continue to trigger.

**Comment by izzyreal** [comment]
Resolved in https://github.com/izzyreal/mpc/commit/0b0425b91d6005e7208ce6ba68c6849eddecb58c, though I think there's still a potential for rare drop-outs.

One alternative approach for  merging recorded input with `Track.events` would be the following:

`Track` has a `vector<Event> eventBuffer`

The `eventBuffer` is merged into `Track.events` every 300 ticks while playing, and when the user hits stop. In a merge we sort the events by tick.

We must ensure that the events have been quantized before entering the buffer. 

When `Track.mergeEventBuffer()` is called while the sequencer is playing/overdubbing/recording, it checks that only events with a tick < sequencer->getTickPos() are merged.

When mergeEventBuffer is called after the sequencer is stopped it merges the whole buffer.
