### ISSUE TITLE
Note repeat footer shows when note repeat not possible

### ISSUE THREAD

**Issue by SxnnyB** [izzyreal/mpc#78]
Observed:
1.Note repeat footer shows when not playing/recording.

Expected:
1. Should only show when playing/recording as note repeat is only possible in these modes.

**Comment by izzyreal** [comment]
A `sequencer.lock()->isPlaying()` is missing somewhere, should be easy to fix.

**Comment by izzyreal** [comment]
Resolved in c5f03c048c048caa9a56b40076d86889c64d3acc.
