### ISSUE TITLE
Verify compatibility with Linux hosts

### ISSUE THREAD

**Issue by izzyreal** [izzyreal/mpc#8]
Patrick Thrasybule on facebook has reported incompatibilities with various Linux hosts while running in Ubuntu.

See if we can get vMPC2000XL running in the following hosts:
* KXStudio Carla
* Ardour
* FL

**Comment by dromer** [comment]
Instead of `FL` you probably mean `LMMS?` ;)

**Comment by izzyreal** [comment]
I probably wrote that after reading https://jstaf.github.io/2018/02/22/flstudio-on-linux.html :D

But yes, `LMMS` is a good suggestion.

**Comment by izzyreal** [comment]
Ardour on Linux doesn't seem to detect the LV2, after placing it in `/usr/lib/lv2`. It doesn't seem to support VST3 on Linux.
Carla detects it fine from there.
LMMS doesn't support LV2 or VST3.
