### ISSUE TITLE
Note repeat drag mouse for velocity feature request

### ISSUE THREAD

**Issue by SxnnyB** [izzyreal/mpc#80]
Observed:
1. While in note repeat + shift locked mode
2. holding left mouse button on pad triggers pad
3. Moving mouse over pad to other velocity points does not change velocity of note repeat triggered sample 

Suggestion:
3. To simulate behaviour of IRL 2000xl dragging mouse to other velocity points should change velocity of note repeat triggered sample as IRL you can vary pressure on pad to change velocity and linked velocity/filter settings.

**Comment by izzyreal** [comment]
Resolved in https://github.com/izzyreal/vmpc-juce/commit/30677faa2df43de2f3fc8755243180b867caf1ac

Will be part of VMPC2000XL 0.4.5 planned for release this month.
